steps:
- id: 'lint'
  name: 'python:3.6'
  args: ['bash', '-c', 'pip install -r requirements_dev.txt && flake8']
- id: 'update-python-dependencies'
  name: 'gcr.io/cloud-builders/gcloud'
  args: ['-c', 'gcloud composer environments update airflowbolcom-544f36a42f5c0d9d --update-pypi-packages-from-file requirements.txt --location europe-west1 --async || true']
  entrypoint: 'bash'
- id: 'upload'
  name: 'gcr.io/cloud-builders/gsutil'
  args: ['-m', 'rsync', '-r', '.', 'gs://europe-west1-training-airfl-b3ce8eaa-bucket/']
